### ISSUE TITLE
CMakeListsのバックアップファイル

### ISSUE THREAD

**Issue by DaikiMaekawa** [open-rdc/Low_Obstacle_Avoidance#8]
@open-rdc/tsukuba-challenge ルードディレクトリにあるCMakeLists.txtがバックアップファイルになっているようですがこれでいいんですか?

**Comment by ShotaroTerato** [comment]
ご指摘ありがとうございます．
ルートディレクトリにあるCMakeLists.txtは使用していないファイルなのでバックアップファイルになっていても問題ありませんでした．単に削除し忘れていたみたいです．
